const { uploadFile } = require('./controller/file')
const { login, register } = require('./controller/sign')
const { addGroup, delGroup, updateGroup } = require('./controller/group')
const { apply, accept, acceptGroup, reject } = require('./controller/apply')
const { getInfo, updateInfo, delFriend, getMsg,getGroupInfo, search } = require('./controller/user')

module.exports = function (router) {
    router
        .post('/login', login)
        .post('/register', register)
        .post('/upload', uploadFile)
        .get('/getinfo', getInfo)
        .post('/updateinfo', updateInfo)
        .post('/apply', apply)
        .post('/accept', accept)
        .post('/acceptgroup', acceptGroup)
        .post('/reject', reject)
        .get('/search', search)
        .post('/delfriend', delFriend)
        .get('/getmsg', getMsg)
        .post('/addgroup', addGroup)
        .post('/delgroup', delGroup)
        .post('/updategroup', updateGroup)
        .get('/getgroupinfo', getGroupInfo)
};
